### ISSUE TITLE
question: about syntax

### ISSUE THREAD

**Issue by saiqulhaq** [midnightmonster/activerecord-summarize#2]
I just take a look at the source code. I am wondering why there is a constant like this
https://github.com/midnightmonster/activerecord-summarize/blob/09d74925afce48d4cd4127de3888c9ed25ff0acb/lib/chainable_result.rb#L112

and this code is hard to understand for me
![image](https://github.com/midnightmonster/activerecord-summarize/assets/1275215/c6d850f5-ef2b-4ad3-82bd-c81554c8199b)

**Comment by midnightmonster** [comment]
@saiqulhaq I'd like to help make it clearer, but I'm not sure what you're asking. I'll give it a shot.

Overall, `ChainableResult` (which I might better have called `FutureResult`) is about being able to work with values that have not actually been calculated yet within a `summarize` block. So each method called on a `ChainableResult` returns another `ChainableResult`, and at the end of a `summarize` block, after `summarize` has built and evaluated the query, it recursively resolves all `ChainableResults` using the values from the query as the base truth.

`method(:method_name)` produces [a Method object](https://rubyapi.org/3.2/o/method). As you can see in the code you screen-captured, we need to call it several times as a block for an iterator, so it's convenient and (I hope) relatively efficient to have it as a constant. I suppose the down-side is that if someone were for some reason extending `ChainableResult` and needed to change `self.resolve_item`, the fact that the rest of the code uses the constant would make it more challenging.

The code in your screen capture is mostly just what's necessary generically to "replay" an arbitrary method call which has been captured via `method_missing` (look at the definition of `method_missing` for how all that is captured). `obj.send(:foo)` is equivalent(-ish) to `obj.foo` (I should have used `public_send` instead, probably), and `*@args` spreads all original positional arguments, `**@opts` spreads all original keyword arguments, and `&@block` passes the block that was passed to the original method call, if any.

The only special sauce there is mapping the positional arguments and transforming the keyword argument values with `&RESOLVE_ITEM`. This mapping/transformation makes it possible to do simple transformations of `ChainableResult` values inside a `summarize` block. For a trivial example:

```ruby
foo_and_bar = Widget.where(blessed: true).summarize do |blessed|
  blessed.count(:foo) + blessed.count(:bar)
end
```

**Comment by midnightmonster** [comment]
It occurs to me that perhaps you _are_ trying to extend `ChainableResult`. I'd be interested to know your use-case so I can advise whether it's really necessary and perhaps make some change to make it easier or unnecessary.

**Comment by midnightmonster** [comment]
I'm closing this issue—feel free to re-open or reach out otherwise if I can help.

**Comment by saiqulhaq** [comment]
thanks a lot for the explanation 
I am learning Ruby by reading your Gem source code 🙏
